- 난수 = Random Number : 신경망에서 꼭 필요한 기능 

현재 가장 많이 쓰이는 방법은 Xavier 초기화와 He 초기화이며 이 방법들은 랜덤하지만 어느 정도 규칙성이 있는 범위 내에서 난수를 지정한다.  
다만 지금은 위의 방법보다 단순하게 난수를 생성하는 방법을 사용해보려 한다.

In [2]:
import tensorflow as tf
rand = tf.random.uniform([1],0,1)
print(rand)

tf.Tensor([0.08479309], shape=(1,), dtype=float32)


tf.random.uniform 함수로 균일 분포의 난수를 얻을 수 있다.  
___
**균일 분포** = 최소값과 최대값 사이의 모든 수가 나올 확률이 동일한 분포
___
처음에 나오는 [1]은 결과값의 shape를 의미한다.  
shape 란 행렬을 구성하는 행, 열등의 차원의 수를 나타낸다.  
shape를 바꿔서 여러 개의 난수를 얻을 수도 있다.  
0과 1은 범위를 나타낸다.  

In [3]:
rand = tf.random.uniform([4],0,1)
print(rand)

tf.Tensor([0.11230731 0.34054625 0.5004761  0.20540786], shape=(4,), dtype=float32)


균일 분포 외에 난수를 얻는 방법 중 중요한 분포로는 정규 분포가 있다.  
___
**정규 분포** = 가운데가 높고 양극단으로 갈수록 낮아져서 종 모양을 그리는 분포
___
정규 분포 난수를 얻기 위해서는 tf.random.normal을 사용하면 된다.


In [4]:
rand = tf.random.normal([4],0,1)
print(rand)

tf.Tensor([-0.06308232  0.7128798  -0.5481068  -0.49383223], shape=(4,), dtype=float32)


균일 분포와는 다르게 1이상의 값도 나오고 음수도 나오는데 이는 정규 분포에서 0과 1이 의미하는것이 다르기 때문이다.  
정규 분포에서 0은 정규 분포의 평균, 1은 정규 분포의 표준 편차를 의미한다.  
평균이 0이고 표준 편차가 1일 때의 정규 분포를 표준정규분포 라고 한다.  
  


두번째, 세번째 인수가 0, 1로 같을 때 균일 분포는 고층 빌딩 모양, 정규 분포는 산 모양의 그래프로 그려진다.

앞에서 말한 Xavier 초기화나 He 초기화는 균일 분포와 정규 분포 중 하나를 택해  
신경망의 초기값을 초기화한다.