## Numpy
파이썬으로 과학 연산을 쉽고 빠르게 할 수 있게 만든 패키지  
파이썬의 기본 데이터 형식과 내장 함수를 이용하는 것보다 다차원 배열 데이터를   
효과적으로 처리할 수 있다

In [1]:
import numpy as np # 모듈 불러오기

### 1차원 배열 생성

In [2]:
data1 = [0,1,2,3,4,5]
a1 = np.array(data1)
a1

array([0, 1, 2, 3, 4, 5])

___
### 실수와 정수가 혼합된 리스트

In [3]:
data2 = [0.1,5,4,12,0.5]
a2 = np.array(data2)
a2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

실수와 정수가 혼합되어 있는 경우 모두 실수로 반환한다

___
### 타입 확인

In [4]:
a1.dtype # int32
a2.dtype # float64

dtype('float64')

___
### 2차원 배열 생성


In [5]:
data3 = ([[1,2,3],[4,5,6],[7,8,9]])
np.array(data3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

___
### 범위 지정해 배열 생성

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

___
### 1차원 배열 >> 2차원 배열로 변경

In [8]:
np.arange(12).reshape(4,3) # 4행 3열

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

___
### 배열의 형태 

In [9]:
b1 = np.arange(12).reshape(4,3)
b1.shape

(4, 3)

In [10]:
b2 = np.arange(5)
b2.shape

(5,)

다차원은 (m,n)의 형태로 1차원은 (m,)의 형태로 출력

___
### linspace()

범위의 시작과 끝을 지정하고 데이터의 개수를 지정해 Numpy() 배열을 생성

In [11]:
np.linspace(1,10,10) # 1부터 10까지 10개의 데이터 생성


array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

___
### 특별한 형태의 배열

#### zeros()

0 만으로 이루어진 배열

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### zeros()를 이용해 2차원 배열 생성

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### ones()

1 만으로 이루어진 배열

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

#### ones() 2차원 배열

In [15]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### 단위행렬

주 대각선이 모두 1이고 나머지는 0인 행렬

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

___
### astype()

배열의 데이터 타입 반환

In [17]:
str_a = np.array(['1','2','3','4','5'])
num_a = str_a.astype(int)
num_a

array([1, 2, 3, 4, 5])

In [18]:
str_a.dtype # <U1 : numpy 데이터의 형식이 유니코드이며, 문자의 수는 최대 1개

dtype('<U1')

In [19]:
num_a.dtype

dtype('int64')

___
### 난수 배열 생성 rand()

0 과 1 사이의 난수 생성

In [20]:
np.random.rand(2,3)

array([[0.92582422, 0.05557088, 0.64974755],
       [0.88608059, 0.04502273, 0.09119683]])

### randint()

지정한 범위에 해당하는 정수로 난수 배열을 생성

In [21]:
np.random.randint(10, size=(3,4))

array([[0, 1, 1, 7],
       [8, 3, 0, 0],
       [7, 6, 2, 8]])