## numpy 연산

In [2]:
import numpy  as np

In [3]:
arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

___
### 기본 연산

In [4]:
arr1 + arr2

array([11, 22, 33, 44])

In [7]:
arr1 - arr2

array([ 9, 18, 27, 36])

In [6]:
arr2 * 2

array([2, 4, 6, 8])

In [8]:
arr2 ** 2

array([ 1,  4,  9, 16])

In [9]:
arr1 * arr2

array([ 10,  40,  90, 160])

In [10]:
arr1 / arr2

array([10., 10., 10., 10.])

**크기를 비교해 참 거짓으로 반환도 가능**

In [11]:
arr1 > 20

array([False, False,  True,  True])

___
### 통계를 위한 연산

In [14]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

#### 배열의 합, 평균

In [15]:
[arr3.sum(), arr3.mean()]

[10, 2.0]

#### 표준편차, 분산

In [16]:
[arr3.std(), arr3.var()]

[1.4142135623730951, 2.0]

#### 최소값, 최대값

In [17]:
[arr3.min(), arr3.max()]

[0, 4]

#### 누적 합, 누적 곱

In [18]:
arr4 = np.arange(1,5)

In [19]:
arr4.cumsum()

array([ 1,  3,  6, 10])

In [20]:
arr4.cumprod()

array([ 1,  2,  6, 24])

___
### 행렬 연산

In [21]:
A = np.array([0,1,2,3]).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [22]:
B = np.array([3,2,0,1]).reshape(2,2)
B


array([[3, 2],
       [0, 1]])

#### 행렬 곱

In [23]:
A.dot(B)

array([[0, 1],
       [6, 7]])

In [24]:
np.dot(A,B)

array([[0, 1],
       [6, 7]])

#### 전치 행렬

In [25]:
np.transpose(A)

array([[0, 2],
       [1, 3]])

In [26]:
A.transpose()

array([[0, 2],
       [1, 3]])

#### 역행렬

In [27]:
np.linalg.inv(A)

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

#### 행렬식

In [28]:
np.linalg.det(A)

-2.0