## 배열 인덱싱

In [2]:
import numpy as np

In [3]:
a1 = np.array([0,10,20,30,40,50])
a1

array([ 0, 10, 20, 30, 40, 50])

### 배열의 위치 지정

In [4]:
a1[0]

0

In [5]:
a1[4]

40

### 배열의 원소 변경

In [6]:
a1[5] = 70
a1

array([ 0, 10, 20, 30, 40, 70])

### 1차원 배열에서 여러 개의 원소 선택

In [7]:
a1[[1,3,4]]

array([10, 30, 40])

### 2차원 배열에서 원소 선택

In [8]:
a2 = np.arange(10,100,10).reshape(3,3)
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [9]:
a2[0,2] # 행 위치 0, 열 위치 2

30

### 2차원 배열의 원소 변경 

In [10]:
a2[2,2] = 95
a2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 95]])

### 행 전체 가져오기

In [11]:
a2[1]

array([40, 50, 60])

### 특정 행 지정해 전체 값 바꾸기

In [13]:
a2[1] = np.array([45,55,65])
a2

array([[10, 20, 30],
       [45, 55, 65],
       [70, 80, 95]])

### 2차원 배열의 여러 원소 선택하기

In [14]:
a2[[0,2],[0,1]]

array([10, 80])

### 배열에 조건 지정

In [15]:
a = np.array([1,2,3,4,5,6])
print(a[a > 3])

[4 5 6]


In [16]:
a[(a % 2) == 0]

array([2, 4, 6])