## 배열 슬라이싱

In [1]:
import numpy as np

배열 [시작_위치 : 끝_위치]

In [3]:
b1 = np.array([0,10,20,30,40,50])
b1

array([ 0, 10, 20, 30, 40, 50])

In [4]:
b1[1:4]

array([10, 20, 30])

In [5]:
b1[:3]

array([ 0, 10, 20])

In [6]:
b1[2:]

array([20, 30, 40, 50])

### 원소 변경

In [8]:
b1[2:5] = np.array([25,35,45])
b1

array([ 0, 10, 25, 35, 45, 50])

In [9]:
b1[3:6] = 60
b1

array([ 0, 10, 25, 60, 60, 60])

### 2차원 배열의 슬라이싱

In [10]:
b2 = np.arange(10,100,10).reshape(3,3)
b2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [11]:
b2[1:3,1:3]

array([[50, 60],
       [80, 90]])

In [12]:
b2[:3,1:]

array([[20, 30],
       [50, 60],
       [80, 90]])

**행 지정 열 슬라이싱**

In [13]:
b2[1][0:2]

array([40, 50])

**슬라이싱 된 배열에 값 지정**

In [14]:
b2[0:2, 1:3] = np.array([[25,35],[55,65]])
b2

array([[10, 25, 35],
       [40, 55, 65],
       [70, 80, 90]])