In [1]:
import pymysql.cursors
import pandas as pd
import numpy as np

In [4]:
conn = pymysql.connect(host='localhost', user='hi', 
                       password='1598', db='tip', charset='utf8',
                       autocommit=True, cursorclass=pymysql.cursors.DictCursor)
try:

   with conn.cursor() as curs:
      sql = "SELECT * from tips;"
      curs.execute(sql)
      rs = curs.fetchall() # 값을 전부 불러옴

      # DB에서 받아온 값을 DataFrame에 넣음

      df = pd.DataFrame(rs)
      print(df)
    
#       df.to_csv('query.csv')

finally:

   conn.close()

     total_bill   tip     sex smoker  day    time  size
0         21.01  3.50    Male     No  Sun  Dinner     3
1         23.68  3.31    Male     No  Sun  Dinner     2
2         24.59  3.61  Female     No  Sun  Dinner     4
3         25.29  4.71    Male     No  Sun  Dinner     4
4          8.77  2.00    Male     No  Sun  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
241       20.65  3.35    Male     No       Dinner     4
242       20.65  3.35    Male     No       Dinner     5
243       16.99  1.01  Female     No  Sun  Dinner     2
244       20.65  3.35    Male     No       Dinner     4
245       20.65  3.35    Male     No       Dinner     5

[246 rows x 7 columns]


In [5]:
df

total_bill   tip     sex smoker  day    time  size
0         21.01  3.50    Male     No  Sun  Dinner     3
1         23.68  3.31    Male     No  Sun  Dinner     2
2         24.59  3.61  Female     No  Sun  Dinner     4
3         25.29  4.71    Male     No  Sun  Dinner     4
4          8.77  2.00    Male     No  Sun  Dinner     2
..          ...   ...     ...    ...  ...     ...   ...
241       20.65  3.35    Male     No       Dinner     4
242       20.65  3.35    Male     No       Dinner     5
243       16.99  1.01  Female     No  Sun  Dinner     2
244       20.65  3.35    Male     No       Dinner     4
245       20.65  3.35    Male     No       Dinner     5

[246 rows x 7 columns]

In [7]:
df.replace('',np.nan,inplace=True)

In [8]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           4
time          0
size          0
dtype: int64

In [9]:
df['tip_rate'] = df['tip']/df['total_bill']

In [10]:
# 문자열들을 변환시켜주는 과정이 필요함
df['sex'].replace({'Female':0, 'Male':1}, inplace=True)
df['smoker'].replace({'No':0, 'Yes':1}, inplace=True)
df['time'].replace({'Lunch':0, 'Dinner':1}, inplace=True)
df['day'].replace({'Thur':0, 'Fri':1, 'Sat':2, 'Sun':3}, inplace=True)

In [11]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  246.000000  246.000000  246.000000  246.000000  242.000000  246.000000   
mean    19.876789    3.013496    0.646341    0.373984    1.727273    0.727642   
std      8.825050    1.374495    0.479080    0.484846    1.152302    0.446081   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.420000    2.000000    0.000000    0.000000    0.250000    0.000000   
50%     17.905000    3.000000    1.000000    0.000000    2.000000    1.000000   
75%     24.075000    3.540000    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  246.000000  246.000000  
mean     2.601626    0.160694  
std      0.979295    0.060787  
min      1.000000    0.035638  
25%      2.000000    0.129616  
50%      2.000000    0.155400  
75%      3.000000    0.189956  
max      6.000000    0.710345

In [12]:
# object type이 있는지 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   total_bill  246 non-null    float64
 1   tip         246 non-null    float64
 2   sex         246 non-null    int64  
 3   smoker      246 non-null    int64  
 4   day         242 non-null    float64
 5   time        246 non-null    int64  
 6   size        246 non-null    int64  
 7   tip_rate    246 non-null    float64
dtypes: float64(4), int64(4)
memory usage: 15.5 KB


In [15]:
from numpy import isnan
from sklearn.impute import SimpleImputer

In [16]:
data = df.values

In [17]:
y = df['tip']

In [18]:
X = df.drop('tip', axis=1)

In [19]:
X.describe()

total_bill         sex      smoker         day        time        size  \
count  246.000000  246.000000  246.000000  242.000000  246.000000  246.000000   
mean    19.876789    0.646341    0.373984    1.727273    0.727642    2.601626   
std      8.825050    0.479080    0.484846    1.152302    0.446081    0.979295   
min      3.070000    0.000000    0.000000    0.000000    0.000000    1.000000   
25%     13.420000    0.000000    0.000000    0.250000    0.000000    2.000000   
50%     17.905000    1.000000    0.000000    2.000000    1.000000    2.000000   
75%     24.075000    1.000000    1.000000    3.000000    1.000000    3.000000   
max     50.810000    1.000000    1.000000    3.000000    1.000000    6.000000   

         tip_rate  
count  246.000000  
mean     0.160694  
std      0.060787  
min      0.035638  
25%      0.129616  
50%      0.155400  
75%      0.189956  
max      0.710345

In [20]:
y.describe()

count    246.000000
mean       3.013496
std        1.374495
min        1.000000
25%        2.000000
50%        3.000000
75%        3.540000
max       10.000000
Name: tip, dtype: float64

In [21]:
data = X.values

In [22]:
y = y.values

In [23]:
X.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [24]:
data[:,4]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1.

In [25]:
sum(np.isnan(data).flatten())

4

In [26]:
sum(np.isnan(y).flatten())

0

In [27]:
imputer = SimpleImputer(strategy='median')

In [28]:
imputer.fit(data)

SimpleImputer(strategy='median')

In [30]:
data_trans = imputer.transform(data)

## RFE

In [31]:
from sklearn.feature_selection import RFE
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVR

In [32]:
estimator=SVR(kernel='linear')

In [33]:
rfe = RFE(estimator, n_features_to_select=4)

In [34]:
selector=rfe.fit(data_trans,y)

In [35]:
for i in range(data_trans.shape[1]):
  print('Column: %d, Selected=%s, Rank: %d' % (i, rfe.support_[i], rfe.ranking_[i]))

Column: 0, Selected=True, Rank: 1
Column: 1, Selected=False, Rank: 2
Column: 2, Selected=True, Rank: 1
Column: 3, Selected=False, Rank: 3
Column: 4, Selected=False, Rank: 4
Column: 5, Selected=True, Rank: 1
Column: 6, Selected=True, Rank: 1


In [36]:
df1=pd.DataFrame(data_trans, columns=['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'])

In [37]:
df1.columns

Index(['total_bill', 'sex', 'smoker', 'day', 'time', 'size', 'tip_rate'], dtype='object')

In [38]:
df_trans = pd.DataFrame(data_trans)

In [39]:
df_trans.isnull().sum()

0    0
1    0
2    0
3    0
4    0
5    0
6    0
dtype: int64

In [40]:
df_trans

0    1    2    3    4    5         6
0    21.01  1.0  0.0  3.0  1.0  3.0  0.166587
1    23.68  1.0  0.0  3.0  1.0  2.0  0.139780
2    24.59  0.0  0.0  3.0  1.0  4.0  0.146808
3    25.29  1.0  0.0  3.0  1.0  4.0  0.186240
4     8.77  1.0  0.0  3.0  1.0  2.0  0.228050
..     ...  ...  ...  ...  ...  ...       ...
241  20.65  1.0  0.0  2.0  1.0  4.0  0.162228
242  20.65  1.0  0.0  2.0  1.0  5.0  0.162228
243  16.99  0.0  0.0  3.0  1.0  2.0  0.059447
244  20.65  1.0  0.0  2.0  1.0  4.0  0.162228
245  20.65  1.0  0.0  2.0  1.0  5.0  0.162228

[246 rows x 7 columns]

## MinMaxScaler

In [41]:
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler

In [42]:
trans=MinMaxScaler()

In [43]:
data.shape

(246, 7)

In [44]:
X_norm=trans.fit_transform(data)

In [45]:
df_norm=pd.DataFrame(X_norm)

In [46]:
df_norm.describe()

0           1           2           3           4           5  \
count  246.000000  246.000000  246.000000  242.000000  246.000000  246.000000   
mean     0.352048    0.646341    0.373984    0.575758    0.727642    0.320325   
std      0.184857    0.479080    0.484846    0.384101    0.446081    0.195859   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.216799    0.000000    0.000000    0.083333    0.000000    0.200000   
50%      0.310746    1.000000    0.000000    0.666667    1.000000    0.200000   
75%      0.439987    1.000000    1.000000    1.000000    1.000000    0.400000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

                6  
count  246.000000  
mean     0.185349  
std      0.090094  
min      0.000000  
25%      0.139287  
50%      0.177502  
75%      0.228718  
max      1.000000

In [47]:
df.describe()

total_bill         tip         sex      smoker         day        time  \
count  246.000000  246.000000  246.000000  246.000000  242.000000  246.000000   
mean    19.876789    3.013496    0.646341    0.373984    1.727273    0.727642   
std      8.825050    1.374495    0.479080    0.484846    1.152302    0.446081   
min      3.070000    1.000000    0.000000    0.000000    0.000000    0.000000   
25%     13.420000    2.000000    0.000000    0.000000    0.250000    0.000000   
50%     17.905000    3.000000    1.000000    0.000000    2.000000    1.000000   
75%     24.075000    3.540000    1.000000    1.000000    3.000000    1.000000   
max     50.810000   10.000000    1.000000    1.000000    3.000000    1.000000   

             size    tip_rate  
count  246.000000  246.000000  
mean     2.601626    0.160694  
std      0.979295    0.060787  
min      1.000000    0.035638  
25%      2.000000    0.129616  
50%      2.000000    0.155400  
75%      3.000000    0.189956  
max      6.000000    0.710345

## StandardScaler

In [48]:
from sklearn.preprocessing import StandardScaler

In [49]:
sc = StandardScaler()

In [50]:
df_sc = sc.fit_transform(data)

In [51]:
df_transform_sc=pd.DataFrame(df_sc)

In [52]:
df_transform_sc.describe().round()

0      1      2      3      4      5      6
count  246.0  246.0  246.0  242.0  246.0  246.0  246.0
mean    -0.0   -0.0   -0.0   -0.0    0.0    0.0   -0.0
std      1.0    1.0    1.0    1.0    1.0    1.0    1.0
min     -2.0   -1.0   -1.0   -2.0   -2.0   -2.0   -2.0
25%     -1.0   -1.0   -1.0   -1.0   -2.0   -1.0   -1.0
50%     -0.0    1.0   -1.0    0.0    1.0   -1.0   -0.0
75%      0.0    1.0    1.0    1.0    1.0    0.0    0.0
max      4.0    1.0    1.0    1.0    1.0    3.0    9.0

## PCA

In [53]:
from sklearn.datasets import make_classification
from sklearn.decomposition import PCA

In [54]:
data_trans.shape

(246, 7)

In [55]:
trans = PCA(n_components=5)

# transform the data
X_dim = trans.fit_transform(data_trans)

# summarize data after the transform
print(X_dim[:5, :])

[[  1.18924702  -1.31681733   0.29410147  -0.36954791  -0.04222359]
 [  3.78754317  -1.15302609  -0.83516503  -0.56866459  -0.23179431]
 [  4.81720445  -1.18883809   1.05158352   0.42330128  -0.70197245]
 [  5.52372259  -1.26730663   1.00629646  -0.24503343   0.0297119 ]
 [-11.0856656   -1.61090901   0.05990868  -0.40774868   0.02084853]]


In [56]:
df_X_dim=pd.DataFrame(X_dim)

In [57]:
df_X_dim.describe().round()

0      1      2      3      4
count  246.0  246.0  246.0  246.0  246.0
mean    -0.0   -0.0    0.0    0.0    0.0
std      9.0    1.0    1.0    0.0    0.0
min    -17.0   -2.0   -2.0   -1.0   -1.0
25%     -7.0   -1.0   -0.0   -0.0   -0.0
50%     -2.0   -0.0   -0.0    0.0    0.0
75%      4.0    1.0    0.0    0.0    0.0
max     31.0    3.0    3.0    1.0    1.0

## Regression Feature Selection:

In [58]:
from sklearn.datasets import make_regression
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression

In [59]:
fs = SelectKBest(score_func=f_regression, k=4)

In [60]:
X_selected = fs.fit_transform(data_trans, y)
print(X_selected.shape)

(246, 4)


In [61]:
df_X_selected = pd.DataFrame(X_selected)

In [62]:
df_X_selected.describe()

0           1           2           3
count  246.000000  246.000000  246.000000  246.000000
mean    19.876789    1.731707    2.601626    0.160694
std      8.825050    1.143380    0.979295    0.060787
min      3.070000    0.000000    1.000000    0.035638
25%     13.420000    1.000000    2.000000    0.129616
50%     17.905000    2.000000    2.000000    0.155400
75%     24.075000    3.000000    3.000000    0.189956
max     50.810000    3.000000    6.000000    0.710345